### ISSUE TITLE
ModuleNotFoundError: No module named 'utilities3'

### ISSUE THREAD

**Issue by lilux618** [zongyi-li/Geo-FNO#7]
root@90f5577d61db:/workspace/Geo-FNO/airfoils# python3 naca_geofno.py 
Traceback (most recent call last):
  File "/workspace/Geo-FNO/airfoils/naca_geofno.py", line 8, in <module>
    from utilities3 import *
ModuleNotFoundError: No module named 'utilities3'  
 
What's wrong with me?

**Comment by MaxGhi8** [comment]
Hello, maybe try to download the file utilities3.py file (found in the main neuraloperator/Geo-FNO folder) and put it in your working directory. Let me now if this solve the issue.

**Comment by samuelgneff** [comment]
@lilux618 I added a setup.py file and did some minor restructuring to avoid any relative imports and moving of files. That way utilities3 is in its own module and available throughout the project. 

I think it would make sense to add a `setup.py` file and a `requirements.txt`. The readme says the project only depends on pytorch >=1.8.0, but there are a number of other required packages to install if you want to run the code.

**Comment by zhaxinmeng** [comment]
utilities3 is in the parent directory of files that importing utilities3, and change "from utilities3 import *" to "from ..utilities3 import *" will solve the error

**Comment by coffecdog** [comment]
(wm_test) star@star-ESC8000A-E11:/mnt/18t/wm/Geo-FNO/elasticity$ python elas_geofno.py
Traceback (most recent call last):
  File "/mnt/18t/wm/Geo-FNO/elasticity/elas_geofno.py", line 8, in <module>
    from utilities3 import *
ModuleNotFoundError: No module named 'utilities3'
(wm_test) star@star-ESC8000A-E11:/mnt/18t/wm/Geo-FNO/elasticity$ 

Brother, I also appeared this mistake, how to solve it. for help
